modLoader="javafml" #mandatory
loaderVersion="[33,)" #mandatory
issueTrackerURL="https://github.com/Andromander/Nifty/issues" #optional
license="GNU Lesser General Public v3"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="nifty" #mandatory
version="3.1" #mandatory
displayName="Nifty" #mandatory
updateJSONURL="https://raw.githubusercontent.com/Andromander/Nifty/master/update.json" #optional
displayURL="https://minecraft.curseforge.com/projects/nifty" #optional
#logoFile="" #optional
credits="Androsa, or AlphaLeaf, your choice." #optional
authors="Androsa" #optional
description='''
A little bit of this and that.
Nifty aims to make your extravagant life of building in vanilla that much better with some fancy decorative blocks. Build a castle with Gold and Diamond Stairs and Slabs, craft some intricate puzzles with Redstone Fences or Slabs, reinforce your home with Obsidian Fences.
The possibilities are...a bit more expansive. Not limitless, but just a little bit of convenience.
'''

[[dependencies.nifty]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[33,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.nifty]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="BOTH"